remote: origin
target-branch: main
chart-repos:
  - argoproj=https://argoproj.github.io/argo-helm/
helm-extra-args: "--timeout 120s"
validate-chart-schema: false
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
