{{- if .Values.argoRunner.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "gordo.argoRunner.fullname" . }}
  labels:
    {{- include "gordo.labels" (dict "context" . "component" .Values.argoRunner.name) | nindent 4 }}
  {{- with .Values.argoRunner.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "gordo.argoRunner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "gordo.argoRunner.serviceAccountName" . }}
    namespace: {{ default "default" .Release.Namespace }}
{{- end }}