{{- if .Values.argoRunner.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "gordo.argoRunner.fullname" . }}
  labels:
    {{- include "gordo.labels" (dict "context" . "component" .Values.argoRunner.name) | nindent 4 }}
  {{- with .Values.argoRunner.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
  - create
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - delete
  - create
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch
- apiGroups:
  - equinor.com
  resources:
  - models
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - equinor.com
  resources:
  - gordos
  verbs:
  - get
  - list
  - update
  - patch
  - watch
- apiGroups:
  - equinor.com
  resources:
  - gordos/status
  verbs:
  - get
  - patch
- apiGroups:
  - equinor.com
  resources:
  - models/status
  verbs:
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
{{- end }}