{{- if .Values.argoRunner.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gordo.argoRunner.serviceAccountName" . }}
  labels:
    {{- include "gordo.labels"  (dict "context" . "component" .Values.argoRunner.name) | nindent 4 }}
  {{- with .Values.argoRunner.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}