apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gordo.controller.fullname" . }}
  labels:
    {{- include "gordo.labels"  (dict "context" . "component" .Values.controller.name) | nindent 4 }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.controller.autoscaling.enabled }}
  replicas: {{ .Values.controller.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gordo.selectorLabels" (dict "context" . "component" .Values.controller.name) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gordo.labels" (dict "context" . "component" .Values.controller.name) | nindent 8 }}
    spec:
      {{- with .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gordo.controller.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.controller.name }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{- include "gordo.image" (dict "context" . "image" .Values.controller.image) }}:{{ default .Chart.AppVersion .Values.controller.image.tag }}"
          imagePullPolicy: {{ default .Values.images.pullPolicy .Values.controller.image.pullPolicy }}
          ports:
            - name: "{{ .Values.controller.portName }}"
              containerPort: {{ .Values.controller.containerPort | int }}
              protocol: TCP
          env:
          {{- $defaultEnvs := fromJson (include "gordo.controller.defaultEnvs" .) -}}
          {{- $env := mustMerge $defaultEnvs .Values.controller.env -}}
          {{- range $name := keys $env | uniq | sortAlpha }}
            - name: {{ $name | quote }}
              value: {{ get $env $name | quote }}
          {{- end }}
          {{- if .Values.controller.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.controller.portName }}
            {{- $probe := .Values.controller.readinessProbe | deepCopy }}
            {{- with omit $probe "enabled" }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.controller.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.controller.portName }}
            {{- $probe := .Values.controller.livenessProbe | deepCopy }}
            {{- with omit $probe "enabled" }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.controller.volumes }}
      volumes:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "gordo.selectorLabels" (dict "context" $ "component" $.Values.controller.name) | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}