{{- if .Values.controller.ingress.enabled -}}
{{- $fullName := include "gordo.controller.fullname" . -}}
{{- $hosts := list -}}
{{- if empty .Values.controller.ingress.hosts -}}
{{- $hosts = append $hosts (include "gordo.ingress.defaultHost" .) -}}
{{- else -}}
{{- $hosts = concat $hosts .Values.controller.ingress.hosts -}}
{{- end -}}
{{- $port := .Values.controller.service.port -}}
{{- if and .Values.controller.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.controller.ingress.annotations "kubernetes.io/ingress.class") }}
    {{- $_ := set .Values.controller.ingress.annotations "kubernetes.io/ingress.class" .Values.controller.ingress.className}}
  {{- end }}
{{- end }}
{{- if eq .Values.controller.ingress.className "nginx" }}
  {{- $_ := set .Values.controller.ingress.annotations "nginx.ingress.kubernetes.io/rewrite-target" "/$1" }}
{{- end }}
{{- $pathPrefix := (include "gordo.controller.pathPrefix" .) -}}
{{ include "gordo.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gordo.labels"  (dict "context" . "component" .Values.controller.name) | nindent 4 }}
  {{- with .Values.controller.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.controller.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.controller.ingress.className }}
  {{- end }}
  {{- if .Values.controller.ingress.tls.enabled }}
  tls:
    {{- with $hosts }}
    hosts:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    secretName: {{.Values.controller.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    {{- range $host := $hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $pathPrefix }}
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName | quote }}
                port:
                  number: {{ $port | int }}
              {{- else }}
              serviceName: {{ $fullName | quote }}
              servicePort: {{ $port | int }}
              {{- end }}
          {{- end }}
{{- end }}
