{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gordo.controller.fullname" . }}
  labels:
    {{- include "gordo.labels"  (dict "context" . "component" .Values.controller.name) | nindent 4 }}
  {{- with .Values.monitoring.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: {{ .Values.controller.service.portName }}
  selector:
    matchLabels:
    {{- include "gordo.selectorLabels" (dict "context" . "component" .Values.controller.name) | nindent 6 }}
{{- end -}}