{{- if .Values.controller.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "gordo.controller.fullname" . }}
  labels:
    {{- include "gordo.labels" (dict "context" . "component" .Values.controller.name) | nindent 4 }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - watch
  apiGroups:
  - equinor.com
  resources:
  - gordos
- verbs:
  - patch
  apiGroups:
  - equinor.com
  resources:
  - gordos/status
- verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - watch
  apiGroups:
  - equinor.com
  resources:
  - models
- verbs:
  - patch
  apiGroups:
  - equinor.com
  resources:
  - models/status
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - patch
  - update
  - list
  - get
- verbs:
  - get
  - list
  - patch
  - watch
  apiGroups:
  - ''
  resources:
  - pods
- verbs:
  - get
  - list
  - patch
  - watch
  apiGroups:
  - argoproj.io
  resources:
  - workflows
{{- end }}