{{- if .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gordo.controller.serviceAccountName" . }}
  labels:
    {{- include "gordo.labels"  (dict "context" . "component" .Values.controller.name) | nindent 4 }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
