apiVersion: v1
kind: Service
metadata:
  name: {{ include "gordo.controller.fullname" . }}
  labels:
    {{- include "gordo.labels"  (dict "context" . "component" .Values.controller.name) | nindent 4 }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: {{ .Values.controller.portName }}
      protocol: TCP
      name: {{ .Values.controller.service.portName }}
  selector:
    {{- include "gordo.selectorLabels" (dict "context" . "component" .Values.controller.name) | nindent 4 }}
