{{- if and .Values.runtime.create .Values.runtime.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  labels:
    {{- include "gordo.labels"  (dict "context" . "component" .Values.runtime.name) | nindent 4 }}
  {{- with .Values.runtime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.runtime.pvc.size }}
{{- if .Values.runtime.pvc.storageClassName }}
{{- if (eq "-" .Values.runtime.pvc.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.runtime.pvc.storageClassName }}"
{{- end }}
{{- end }}
{{- end }}